### ISSUE TITLE
Request for Pretrained Weights to Run Your Project Code

### ISSUE THREAD

**Issue by tuin33** [Xianhua-He/cvpr2024-face-anti-spoofing-challenge#1]
I am really impressed with your work! I am interested in running the code you have shared, but I noticed that the pretrained weights are not included in the repository.  
  
Could you please provide the pretrained weights for this project? They would be extremely helpful for me to replicate your results and continue my research.  
  
Thank you very much for your time and effort in sharing your code!

**Comment by Xianhua-He** [comment]
@tuin33 
Thank you very much for your interest in my work.

If you are asking about the pretrained model, we use ImageNet's Resnet50 pretrained model under the three protocols. 

If you are asking about the model I trained under each protocol, then I will update the weight link of the model in the Readme later.

**Comment by tuin33** [comment]
> @tuin33 Thank you very much for your interest in my work.
> 
> If you are asking about the pretrained model, we use ImageNet's Resnet50 pretrained model under the three protocols.
> 
> If you are asking about the model I trained under each protocol, then I will update the weight link of the model in the Readme later.

Yes, I am indeed interested in the model you trained under each protocol. Thank you for your prompt response and for sharing the pretrained model you used. Thank you again for your work!

**Comment by Xianhua-He** [comment]
> > @tuin33 Thank you very much for your interest in my work.
> > If you are asking about the pretrained model, we use ImageNet's Resnet50 pretrained model under the three protocols.
> > If you are asking about the model I trained under each protocol, then I will update the weight link of the model in the Readme later.
> 
> Yes, I am indeed interested in the model you trained under each protocol. Thank you for your prompt response and for sharing the pretrained model you used. Thank you again for your work!

The link to the model weight file trained under each protocol has been updated in the Readme. I hope it will be helpful to your research.
