### ISSUE TITLE
Model Testing on Protocol Dataset Produces Opposite Results

### ISSUE THREAD

**Issue by tuin33** [Xianhua-He/cvpr2024-face-anti-spoofing-challenge#2]
Hi! We tested your model on the Protocol part of the dataset that provided by the challenge. However, results outputed by the model is opposite with the label files. Therefore, we would like to confirm that weather the model is applied in the currect dataset. We also noticed that while we take the min value index in outputs instead of the max value, results seem like to be normal. The confuse matrix we get is shown below. Thanks for your time!
The confuse matrix of taking the max value:
![QQ截图20240426112231](https://github.com/Xianhua-He/cvpr2024-face-anti-spoofing-challenge/assets/81750006/f2e3f9d4-264c-4ee5-8b37-c5a9d2419e62)
The confuse matrix of taking the min value:
![QQ截图20240426112103](https://github.com/Xianhua-He/cvpr2024-face-anti-spoofing-challenge/assets/81750006/6dcfbb9f-e749-4fbb-8300-ff781c5eabc7)

**Comment by Xianhua-He** [comment]
@tuin33 
We are using the data set provided by the competition, Label: live=0, fake=1. The label may be opposite to your data set, but the data should be consistent. For more detailed instructions, please refer to: https://codalab.lisn.upsaclay.fr/competitions/17490#learn_the_details-evaluation. 
The official results when evaluating apcer and bpcer were opposite, and we changed it to be correct.

**Comment by Xianhua-He** [comment]
@tuin33 
Hello, I wonder if your problem has been solved? I just learned from the competition organizer that the labels provided by the dataset for the competition are reversed.
I am glad that you are interested in my work. If it is helpful to your research, you are welcome to cite my work.
If you have any other details you would like to know, please feel free to raise an issue or add me on WeChat：13381144493
