### ISSUE TITLE
Code for 4th Face Anti-spoofing Challenge@CVPR2023

### ISSUE THREAD

**Issue by kiendn1** [Xianhua-He/cvpr2024-face-anti-spoofing-challenge#5]
As I know you win the second in 4th Face Anti-spoofing Challenge@CVPR2023, task Face Anti-spoofing in the wild. Could you share your code? Or you could share your technical report?

**Comment by Xianhua-He** [comment]
@kiendn1 

I'm sorry, I only have the PPT of the competition report, and the training code is not organized. The core of our competition method last year was self-supervised pre-training based on contrastive learning.

PPT url:  https://docs.google.com/presentation/d/12hsb92W69xA4i2MMFsy_4EORW4pbFWdS/edit?usp=drive_link&ouid=117745389068059170943&rtpof=true&sd=true

I hope it can be helpful to you.

**Comment by kiendn1** [comment]
@Xianhua-He
Thank you for sharing your PPT of the competition report. 
Could you provide the weights of your pretrained Swin V2 Tiny and Swin V2 Large models?
