### ISSUE TITLE
在轻量化模型上的尝试

### ISSUE THREAD

**Issue by Desmond-97** [Xianhua-He/cvpr2024-face-anti-spoofing-challenge#7]
Great work！
我使用了贵团队提供的适用于广泛场景的full-resnet50模型，效果非常好，但在我的部署环境下推理速度较慢。请问您在更轻量的模型上有所尝试吗？例如mobilenetv3_small。我在自己的数据集上训练mobilenetv3_small效果并不好。
请问您后续会开源更轻量化的模型吗？

**Comment by Xianhua-He** [comment]
@Desmond-97  已开源mobilenetv3和shufflenetv2模型，并更新了一下测试代码，你需要git pull拉一下最新的代码即可测试了。

**Comment by Desmond-97** [comment]
感谢作者！轻量化模型的效果也非常棒，部署后推理速度很快！
